name: virtual_glasses_tryon
description: A virtual glasses try-on app for web and mobile

environment:
  sdk: '>=3.0.0 <4.0.0'
  # flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.13.1
  vector_math: ^2.1.4
  cross_file: ^0.3.3
  camera: ^0.11.1
  # The default Android implementation from camera_android_camerax doesn't support the required image format.
  camera_android: ^0.10.10+1
  camera_web: ^0.3.5
  permission_handler: ^12.0.0+1
  google_mlkit_commons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  freezed_annotation: ^3.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.8

flutter:
  assets:
    - assets/glasses/
    # - assets/models/